basePath: /api
definitions:
  market.PoolData:
    properties:
      closeTime:
        type: string
      id:
        type: string
      openTime:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Candly server API.
  termsOfService: http://swagger.io/terms/
  title: Candly
  version: "1.0"
paths:
  /pool:
    get:
      description: get the details of all the pools
      operationId: get-pools
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/market.PoolData'
        "400":
          description: Bad Request
      summary: Get pools
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
