basePath: /api
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Candly server API.
  termsOfService: http://swagger.io/terms/
  title: Candly
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get details of all pools.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
      summary: Get all the pools.
      tags:
      - pools
swagger: "2.0"
