// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: bets.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPool = `-- name: CreatePool :exec
INSERT INTO pools (
  id, open_time, close_time, type
) VALUES (
  $1, $2, $3, $4
)
`

type CreatePoolParams struct {
	ID        string
	OpenTime  pgtype.Int8
	CloseTime pgtype.Int8
	Type      PoolType
}

func (q *Queries) CreatePool(ctx context.Context, arg CreatePoolParams) error {
	_, err := q.db.Exec(ctx, createPool,
		arg.ID,
		arg.OpenTime,
		arg.CloseTime,
		arg.Type,
	)
	return err
}

const updatePool = `-- name: UpdatePool :exec
UPDATE pools SET open_price=$2, close_price=$3
WHERE id=$1
`

type UpdatePoolParams struct {
	ID         string
	OpenPrice  pgtype.Numeric
	ClosePrice pgtype.Numeric
}

func (q *Queries) UpdatePool(ctx context.Context, arg UpdatePoolParams) error {
	_, err := q.db.Exec(ctx, updatePool, arg.ID, arg.OpenPrice, arg.ClosePrice)
	return err
}
