CREATE TABLE IF NOT EXISTS users(
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
    (START WITH 1111 INCREMENT BY 3),
    phone VARCHAR (13) UNIQUE NOT NULL,
    email VARCHAR (100),
    name VARCHAR (100) 
)